spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

  jwt:
    secret: thisIsASecretKeyForJWTGenerationYouShouldUseItOnlyLocal
    access-token-validity: 1800000 # 30분
    refresh-token-validity: 604800000  # 7일
